apiVersion: v1
data:
  otelcollector-config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc: # on port 4317

    processors:
      batch: {}
      resourcedetection:
        detectors: [gcp]
        override: false

    exporters:
      debug:

      googlecloud:
        log:
          default_log_name: opentelemetry.io/collector-exported-log

      otlp:
        endpoint: tempo-distributor:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch,resourcedetection]
          exporters: [debug,googlecloud,otlp]
kind: ConfigMap
metadata:
  name: otel-collector
  namespace: observability
