apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: docker-desktop
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-prometheus'
    spec:
      project: default
      source:
        repoURL: https://github.com/makocchan0509/sample-argocd.git
        targetRevision: HEAD
        path: prometheus
      destination:
        server: '{{url}}'
        namespace: observability