apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: wf-event-trigger
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-event-trigger
subjects:
- kind: ServiceAccount
  name: wf-event-trigger
  namespace: argo
