apiVersion: v1
kind: Secret
metadata:
  name: wf-event-trigger.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: wf-event-trigger
type: kubernetes.io/service-account-token