apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wf-event-trigger
  namespace: argo
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workfloweventbindings
    verbs:
    - list
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create