apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: autopilot-cluster-1
        url: https://connectgateway.googleapis.com/v1beta1/projects/92935634485/locations/global/gkeMemberships/autopilot-cluster-1
  template:
    metadata:
      name: '{{cluster}}-gateway-api'
    spec:
      project: default
      source:
        repoURL: https://github.com/makocchan0509/sample-argocd.git
        targetRevision: HEAD
        path: gateway
      destination:
        server: '{{url}}'
        namespace: gw-infra