apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-trace-api-2
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: autopilot-cluster-1
        url: https://connectgateway.googleapis.com/v1beta1/projects/92935634485/locations/global/gkeMemberships/autopilot-cluster-1
      - cluster: autopilot-cluster-2
        url: https://connectgateway.googleapis.com/v1beta1/projects/92935634485/locations/global/gkeMemberships/autopilot-cluster-2
  template:
    metadata:
      name: '{{cluster}}-sample-trace-api-2'
    spec:
      project: default
      source:
        repoURL: https://github.com/makocchan0509/sample-argocd.git
        targetRevision: HEAD
        path: sample-app-2
      destination:
        server: '{{url}}'
        namespace: default