apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-go-trace-api-2
  name: sample-go-trace-api-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-trace-api-2
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-go-trace-api-2
    spec:
      containers:
      - image: asia-northeast1-docker.pkg.dev/ca-masem-test/any-container/sample-go-trace-api:v4.0.0
        name: sample-go-trace-api
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: PROJECT_ID
            value: ca-masem-test
          - name: APP_NAME
            value: sample-go-trace-api-2
          - name: APP_VERSION
            value: v3.0.0
          - name: APP_PORT
            value: "8080"
          - name: ENDPOINT
            value: "http://sample-go-trace-api-1.default.svc.cluster.local:8080/api/v1/sleep"
          - name: OTEL_AGENT_ENDPOINT
            value: otel-collector.observability.svc.cluster.local:4317
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-go-trace-api-2
  name: sample-go-trace-api-2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: sample-go-trace-api-2
